### ISSUE TITLE
fix/forgotten comma in `CircularArc.to_vtk`

### ISSUE THREAD

**Issue by germa89** [pyvista/pyiges#20]
Hi

Recent update in Pyvista raised that there is a forgotten comma in the method `CircularArc.to_vtk` (https://github.com/pyvista/pyiges/blob/1df9a8d6004e5f6d8aa37638706ef41d31a08f53/pyiges/geometry.py#L633 ).

I'm not sure why now it is highlighted.

**Comment by germa89** [comment]
I created the PR in my own fork:

https://github.com/pyvista/pyiges/pull/21

**Comment by germa89** [comment]
I'm trying to find out why that error is raised now:

- I checked the pyiges offending line and it was written 17 months ago:
https://github.com/pyvista/pyiges/blame/1df9a8d6004e5f6d8aa37638706ef41d31a08f53/pyiges/geometry.py#L633 

- I check also the method `pv.CircularArc` the line where it checks the inputs and it was also written long ago:
https://github.com/pyvista/pyvista/blame/cb31edb71be38aac3cb601917f2f26813b1fce9a/pyvista/utilities/geometric_objects.py#L950

- I also checked if the function has been modified, and it hasn't been recently:
https://github.com/pyvista/pyvista/blame/cb31edb71be38aac3cb601917f2f26813b1fce9a/pyvista/utilities/errors.py#L328-L335

I guess I'm missing something here.

Anyway, the proposed PR solves the issue.

**Comment by akaszynski** [comment]
> I'm trying to find out why that error is raised now:
> 
> * I checked the pyiges offending line and it was written 17 months ago:
>   https://github.com/pyvista/pyiges/blame/1df9a8d6004e5f6d8aa37638706ef41d31a08f53/pyiges/geometry.py#L633
> * I check also the method `pv.CircularArc` the line where it checks the inputs and it was also written long ago:
>   https://github.com/pyvista/pyvista/blame/cb31edb71be38aac3cb601917f2f26813b1fce9a/pyvista/utilities/geometric_objects.py#L950
> * I also checked if the function has been modified, and it hasn't been recently:
>   https://github.com/pyvista/pyvista/blame/cb31edb71be38aac3cb601917f2f26813b1fce9a/pyvista/utilities/errors.py#L328-L335
> 
> I guess I'm missing something here.
> 
> Anyway, the proposed PR solves the issue.

The change was `pyvista` enforces inputs much more strictly in https://github.com/pyvista/pyvista/pull/1971
