### ISSUE TITLE
delta based on curvature

### ISSUE THREAD

**Issue by RubendeBruin** [pyvista/pyiges#26]
I need to convert an igs file to a mesh. The file has some curved surfaces and some flat ones. 
My preference would be to convert the flat surfaces to a minimum amount of triangles while keeping a higher resolution in the areas with higher curvature.

I can do this iteratively by checking the normals of adjacent triangles after conversion in RationalBSplineSurface.to_vtk() but am pretty sure there is a better way.

Willing to make a PR and work on the implementation

**Comment by RubendeBruin** [comment]
Did dig in a bit

points coordinates can be evaluated with 
```python
point1 = surf.evaluate_single((0,0))
point2 = surf.evaluate_single((0,1))
point3 = surf.evaluate_single((1,1))
point4 = surf.evaluate_single((1,0))
```

normals with:
```python
normal = operations.normal(surf, (0., 0.))
print(f'Normal = {normal}')
```

-  evaluate the normal at the four corners and base the delta on the angle. This is not correct if there are "internal bumps" in the nurbs, but in my model that happens not to be the case.
- also check the maximum distance between the four corners of the surface. If that is small then it still may not make much sense to use a small delta.



Probably a better approach: https://www.researchgate.net/publication/270267482_The_Quick_Measure_of_a_Nurbs_Surface_Curvature_for_Accurate_Triangular_Meshing

**Comment by whophil** [comment]
@RubendeBruin the OpenCASCADE library offers this type of meshing out of the box, if you are willing to crack that open. There are a number of Python interfaces for it, see:
- https://github.com/trelau/pyOCCT
- https://github.com/CadQuery/OCP

An example:
https://github.com/CadQuery/cadquery/blob/master/cadquery/occ_impl/shapes.py#L1245

**Comment by akaszynski** [comment]
I'd like to emphasize that this IGES reader isn't really great and I'd really recommend pyOCCT or OCP as @whophil pointed out. This was released to the public to support anyone who wanted to work with IGES files directly with a *very* simplified interface.
