### ISSUE TITLE
Request about extension of example data to increase test coverage to 100%

### ISSUE THREAD

**Issue by mikamove** [pyvista/pyiges#31]
I separated this issue from #28 for clarity and mentioned it there as a subtask. I hope this way the discussion there can be kept short, because this here is a rather small task which can be solved faster compared to the whole #28 

As mentioned in #30 I could easily increase coverage further to nearly **100%** if we had reference files containing the entity types listed below. I went through some basic FreeCAD Tutorials and managed to create an example for the `ConicArc` type, but for the other types I would need help, as I have unfortunately not enough technical knowledge to create such files and also I don't know any sources for existing files, which are clearly licensed such that adding them here as reference data would be OK. 

As long as we had IGES files containing the following types, the coverage would become nearly 100% independent of the concrete details of the data:

| geometry type                   | IGES type number |
| ------------------------------- | ------------ |
| **geometry.EdgeList**              |          504 |
| **geometry.VertexList**             |          502 |
| geometry.ConicArc               |          104 |
| **geometry.Face**                   |          510 |
| **geometry.Loop**                   |          508 |

Do You have expertise in creating such files or knowledge about from where to obtain those? If yes, and You'd just add them to `main`, I'd be happy to add tests based on these files. Note that this data does not neccessarily has to be added to the `pyiges/examples` directory (which is packaged into the module) but could instead just be dropped to some independent directory (e.g. `tests/examples`) which is only used locally for testing, so we are not neccessarily talking about the "visible" examples of the module and the examples don't need to show something interesting or complex from an engineer's perspective.

**Comment by banesullivan** [comment]
I'm afraid I have no experience with these formats and making proper test data. @akaszynski is probably better suited for this but his time is definitely limited these days

**Comment by akaszynski** [comment]
Don't push for getting perfect coverage. IGES is a deprecated format with legacy support; we're doing people a favor trying to keep this in maintenance.

Go for decent coverage, but don't feel like you need 100%.

**Comment by banesullivan** [comment]
Where does coverage currently stand? I see the CI jobs are generate coverage reports... we should at a minimum print those out at the end of the CI job

**Comment by mikamove** [comment]
@banesullivan Currently we are at **85%** of the folder `pyiges/`.

**Comment by mikamove** [comment]
@banesullivan I offer this as a prerequisite of #28 to give You trust in the review, if You need no further coverage, You can also close this and I'll skip this step in #28. Later, when I'm on my laptop I can also append the current coverage report here.

**Comment by banesullivan** [comment]
IMO, 85% is beyond satisfactory! (well anything over 70% actually)

**Comment by mikamove** [comment]
This are the coverage details, more inside [htmlcov.tar.gz](https://github.com/pyvista/pyiges/files/11254041/htmlcov.tar.gz)

![grafik](https://user-images.githubusercontent.com/17496175/232571237-b0ec6ca8-48b6-42fa-8b79-0ce71c3de13a.png)

**Comment by mikamove** [comment]
@banesullivan Let me know if You need more Info, otherwise feel free to close this. In the latter case, I'd just include testing the single `ArcConic` mentioned above just in the big PR, as I think a separate one would be too much overhead.

**Comment by akaszynski** [comment]
>  I'd just include testing the single ArcConic mentioned above just in the big PR...

Agreed. It's small enough that we don't need to split it up.
