### ISSUE TITLE
Numer Format of Iges Data

### ISSUE THREAD

**Issue by msc-turb** [pyvista/pyiges#8]
Hi,

when I export an iges file out of Creo, the digits are exportet in the following format:
`5.534744625280D0,1.466545010164D1,-3.170499938074D-2,               1791P   6432`

When reading this into pyiges, it can't be converted to float (seems reasonable).
As a workaround I replaced all 'D' with 'E', but only in the P-Section.

I have no clue why Creo exports it with a D. But all programs can read this format.

Regards,
Martin

**Comment by akaszynski** [comment]
Please check if this was fixed in #13 (you'll have to checkout master).  New release should come soon.

**Comment by akaszynski** [comment]
Please install `pyiges==0.2.0` with:

```
pip install pyiges -U
```

And let me know if the release solves the issue.

**Comment by msc-turb** [comment]
Thanks for the fix, I have tried it and it worked!
